config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'

  get     '/help',          to: 'static_pages#help'
  get     '/about',         to: 'static_pages#about'
  get     '/contact',       to: 'static_pages#contact'
  get     '/signup',        to: 'users#new'
  post    '/signup',        to: 'users#create'
  get     '/login',         to: 'sessions#new'
  post    '/login',         to: 'sessions#create'
  delete  '/logout',        to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,              only: [:edit, :update]
  before_action :valid_user,            only: [:edit, :update]
  before_action :check_expiration,      only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions."
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found."
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "Password has been reset."
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  # Before filters.

  def get_user
    @user = User.find_by(email: params[:email])
  end

  # Confirms a valid user.
  def valid_user
    unless (@user && @user.activated? &&
            @user.authenticated?(:reset, params[:id]))
      redirect_to root_url
    end
  end

  # Checks expiration of reset token.
  def check_expiration
    if @user.password_reset_expired?
      flash[:danger] = "Password reset has been expired."
      redirect_to new_password_reset_url
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "Reset password") %>

<div class="columns is-centered">
  <div class="column is-half">
    <h3 class="subtitle is-3">Reset password</h3>
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= hidden_field_tag :email, @user.email %>

      <div class="field">
        <div class="control">
          <%= f.label :password, class: 'label' %>
          <%= f.password_field :password, class: 'input' %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.label :password_confirmation, "Confirmation", class: 'label' %>
          <%= f.password_field :password_confirmation, class: 'input' %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.submit "Update password", class: 'button is-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>

<div class="columns is-centered">
  <div class="column is-half">
    <h3 class="subtitle is-3">Forgot password</h3>
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <div class="field">
        <div class="control">
          <%= f.label :email, class: 'label' %>
          <%= f.email_field :email, class: 'input' %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.submit "Submit", class: 'button is-info is-outlined' %>
        </div>
      </div>
    <% end %>
  </div>
</div>