config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'

  get     '/help',          to: 'static_pages#help'
  get     '/about',         to: 'static_pages#about'
  get     '/contact',       to: 'static_pages#contact'
  get     '/signup',        to: 'users#new'
  post    '/signup',        to: 'users#create'
  get     '/login',         to: 'sessions#new'
  post    '/login',         to: 'sessions#create'
  delete  '/logout',        to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
        The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar is-primary is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to "sample app", root_path, id: "logo", class: "navbar-item" %>
      <div class="navbar-burger" data-target="main-navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div class="navbar-menu" id="main-navbar">
      <div class="navbar-start">
        <%= link_to "Home", root_path, class: "navbar-item" %>
        <%= link_to "Help", help_path, class: "navbar-item" %>
        <%= link_to "About", about_path, class: "navbar-item" %>
        <%= link_to "Contact", contact_path, class: "navbar-item" %>
      </div>
      <div class="navbar-end">
        <% if logged_in? %>
          <%= link_to "Users", users_path, class: "navbar-item" %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Account</a>
            <div class="navbar-dropdown is-right">
              <%= link_to "Profile", current_user, class: "navbar-item" %>
              <%= link_to "Settings", edit_user_path(current_user), class: "navbar-item" %>
              <hr class="navbar-divider">
              <%= link_to "Log out", logout_path, class: "navbar-item", method: :delete %>
            </div>
          </div>
        <% else %>
          <%= link_to "Log in", login_path, class: "navbar-item" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |msg_type, msg| %>
      <div class="notification is-radiusless is-<%= msg_type %> has-text-centered">
        <%= msg %>
      </div>
    <% end %>

    <%= yield :body %>

    <div id="app" class="section">
      <div class="container">
        <%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>